package com.acme.paas.common.model.adfbc.views;

import com.acme.paas.fwk.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 16:16:16 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxcusLookupTypesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxcusLookupTypesVOImpl() {
    }

    /**
     * Returns the variable value for pLookupType.
     * @return variable value for pLookupType
     */
    public String getpLookupType() {
        return (String)ensureVariableManager().getVariableValue("pLookupType");
    }

    /**
     * Sets <code>value</code> for variable pLookupType.
     * @param value value to bind as pLookupType
     */
    public void setpLookupType(String value) {
        ensureVariableManager().setVariableValue("pLookupType", value);
    }

    /**
     * Returns the variable value for pDescription.
     * @return variable value for pDescription
     */
    public String getpDescription() {
        return (String)ensureVariableManager().getVariableValue("pDescription");
    }

    /**
     * Sets <code>value</code> for variable pDescription.
     * @param value value to bind as pDescription
     */
    public void setpDescription(String value) {
        ensureVariableManager().setVariableValue("pDescription", value);
    }
}
