package com.acme.paas.common.model.adfbc.views;

import com.acme.paas.fwk.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 16:16:54 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxcusLookupValuesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxcusLookupValuesVOImpl() {
    }

    /**
     * Returns the bind variable value for pLookupType.
     * @return bind variable value for pLookupType
     */
    public String getpLookupType() {
        return (String)getNamedWhereClauseParam("pLookupType");
    }

    /**
     * Sets <code>value</code> for bind variable pLookupType.
     * @param value value to bind as pLookupType
     */
    public void setpLookupType(String value) {
        setNamedWhereClauseParam("pLookupType", value);
    }

    /**
     * Returns the bind variable value for pLookupCode.
     * @return bind variable value for pLookupCode
     */
    public String getpLookupCode() {
        return (String)getNamedWhereClauseParam("pLookupCode");
    }

    /**
     * Sets <code>value</code> for bind variable pLookupCode.
     * @param value value to bind as pLookupCode
     */
    public void setpLookupCode(String value) {
        setNamedWhereClauseParam("pLookupCode", value);
    }

    /**
     * Returns the variable value for pMeaning.
     * @return variable value for pMeaning
     */
    public String getpMeaning() {
        return (String)ensureVariableManager().getVariableValue("pMeaning");
    }

    /**
     * Sets <code>value</code> for variable pMeaning.
     * @param value value to bind as pMeaning
     */
    public void setpMeaning(String value) {
        ensureVariableManager().setVariableValue("pMeaning", value);
    }

    /**
     * Returns the variable value for pDescription.
     * @return variable value for pDescription
     */
    public String getpDescription() {
        return (String)ensureVariableManager().getVariableValue("pDescription");
    }

    /**
     * Sets <code>value</code> for variable pDescription.
     * @param value value to bind as pDescription
     */
    public void setpDescription(String value) {
        ensureVariableManager().setVariableValue("pDescription", value);
    }

    /**
     * Returns the variable value for pEnabled.
     * @return variable value for pEnabled
     */
    public String getpEnabled() {
        return (String)ensureVariableManager().getVariableValue("pEnabled");
    }

    /**
     * Sets <code>value</code> for variable pEnabled.
     * @param value value to bind as pEnabled
     */
    public void setpEnabled(String value) {
        ensureVariableManager().setVariableValue("pEnabled", value);
    }
}
