package com.acme.paas.properties.model.adfbc.services.client;

import com.acme.paas.properties.model.adfbc.services.common.PAASPropertiesAM;

import java.util.ArrayList;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 21:24:34 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAASPropertiesAMClient extends ApplicationModuleImpl implements PAASPropertiesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PAASPropertiesAMClient() {
    }


    public void initialiseCreate() {
        Object _ret =
            this.riInvokeExportedMethod(this,"initialiseCreate",null,null);
        return;
    }

    public void initialiseEdit(ArrayList structList) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initialiseEdit",new String [] {"java.util.ArrayList"},new Object[] {structList});
        return;
    }

    public void saveTransaction(Boolean clearCache) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveTransaction",new String [] {"java.lang.Boolean"},new Object[] {clearCache});
        return;
    }

    public Boolean isTransactionDirty() {
        Object _ret =
            this.riInvokeExportedMethod(this,"isTransactionDirty",null,null);
        return (Boolean)_ret;
    }
}
