package com.acme.paas.common.model.adfbc.services;

import com.acme.paas.common.model.adfbc.views.lov.EmployeesLOVVOImpl;
import com.acme.paas.fwk.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 07 21:14:59 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAASCommonLOVAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PAASCommonLOVAMImpl() {
    }

    /**
     * Container's getter for EmployeesLOVVO1.
     * @return EmployeesLOVVO1
     */
    public EmployeesLOVVOImpl getEmployeesLOVVO1() {
        return (EmployeesLOVVOImpl)findViewObject("EmployeesLOVVO1");
    }
}
