package com.acme.paas.properties.model.adfbc.services.common;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 21:24:34 BST 2018
// ---------------------------------------------------------------------
public interface PAASPropertiesAM extends ApplicationModule {
    void initialiseCreate();

    void initialiseEdit(ArrayList structList);

    void saveTransaction(Boolean clearCache);

    Boolean isTransactionDirty();
}
