package com.acme.paas.properties.model.adfbc.views;

import com.acme.paas.fwk.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 20:25:34 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonPropertyDefPVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PersonPropertyDefPVOImpl() {
    }
}
