package com.acme.paas.properties.model.adfbc.views;

import com.acme.paas.fwk.ViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 15:53:24 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxcusPersonPropertiesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PersonPropertyId {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPersonPropertyId();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPersonPropertyId((Number)value);
            }
        }
        ,
        PersonId {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPersonId();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPersonId((Number)value);
            }
        }
        ,
        PersonPropertyType {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPersonPropertyType();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPersonPropertyType((String)value);
            }
        }
        ,
        PersonPropertyValue {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPersonPropertyValue();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPersonPropertyValue((String)value);
            }
        }
        ,
        Status {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        StartDateActive {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getStartDateActive();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setStartDateActive((Date)value);
            }
        }
        ,
        EndDateActive {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getEndDateActive();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setEndDateActive((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        FirstName {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getFirstName();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        LastName {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getLastName();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FullName {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getFullName();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setFullName((String)value);
            }
        }
        ,
        PropertyTypeMeaning {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPropertyTypeMeaning();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPropertyTypeMeaning((String)value);
            }
        }
        ,
        PersonPropertyValueLov {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPersonPropertyValueLov();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPersonPropertyValueLov((String)value);
            }
        }
        ,
        PropertyValue {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getPropertyValue();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setPropertyValue((String)value);
            }
        }
        ,
        StatusMeaning {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getStatusMeaning();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setStatusMeaning((String)value);
            }
        }
        ,
        EmployeesVO1 {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getEmployeesVO1();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeesLOVVO1 {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getEmployeesLOVVO1();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeesLOVVO2 {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getEmployeesLOVVO2();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxcusLookupValuesVO1 {
            public Object get(XxcusPersonPropertiesVORowImpl obj) {
                return obj.getXxcusLookupValuesVO1();
            }

            public void put(XxcusPersonPropertiesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxcusPersonPropertiesVORowImpl object);

        public abstract void put(XxcusPersonPropertiesVORowImpl object,
                                 Object value);

        public int index() {
            return XxcusPersonPropertiesVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return XxcusPersonPropertiesVORowImpl.AttributesEnum.firstIndex() + XxcusPersonPropertiesVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = XxcusPersonPropertiesVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERSONPROPERTYID = AttributesEnum.PersonPropertyId.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PERSONPROPERTYTYPE = AttributesEnum.PersonPropertyType.index();
    public static final int PERSONPROPERTYVALUE = AttributesEnum.PersonPropertyValue.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STARTDATEACTIVE = AttributesEnum.StartDateActive.index();
    public static final int ENDDATEACTIVE = AttributesEnum.EndDateActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int PROPERTYTYPEMEANING = AttributesEnum.PropertyTypeMeaning.index();
    public static final int PERSONPROPERTYVALUELOV = AttributesEnum.PersonPropertyValueLov.index();
    public static final int PROPERTYVALUE = AttributesEnum.PropertyValue.index();
    public static final int STATUSMEANING = AttributesEnum.StatusMeaning.index();
    public static final int EMPLOYEESVO1 = AttributesEnum.EmployeesVO1.index();
    public static final int EMPLOYEESLOVVO1 = AttributesEnum.EmployeesLOVVO1.index();
    public static final int EMPLOYEESLOVVO2 = AttributesEnum.EmployeesLOVVO2.index();
    public static final int XXCUSLOOKUPVALUESVO1 = AttributesEnum.XxcusLookupValuesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxcusPersonPropertiesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PersonPropertyId.
     * @return the PersonPropertyId
     */
    public Number getPersonPropertyId() {
        return (Number) getAttributeInternal(PERSONPROPERTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonPropertyId.
     * @param value value to set the  PersonPropertyId
     */
    public void setPersonPropertyId(Number value) {
        setAttributeInternal(PERSONPROPERTYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonId.
     * @return the PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonId.
     * @param value value to set the  PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonPropertyType.
     * @return the PersonPropertyType
     */
    public String getPersonPropertyType() {
        return (String) getAttributeInternal(PERSONPROPERTYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonPropertyType.
     * @param value value to set the  PersonPropertyType
     */
    public void setPersonPropertyType(String value) {
        setAttributeInternal(PERSONPROPERTYTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonPropertyValue.
     * @return the PersonPropertyValue
     */
    public String getPersonPropertyValue() {
        return (String) getAttributeInternal(PERSONPROPERTYVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonPropertyValue.
     * @param value value to set the  PersonPropertyValue
     */
    public void setPersonPropertyValue(String value) {
        setAttributeInternal(PERSONPROPERTYVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StartDateActive.
     * @return the StartDateActive
     */
    public Date getStartDateActive() {
        return (Date) getAttributeInternal(STARTDATEACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StartDateActive.
     * @param value value to set the  StartDateActive
     */
    public void setStartDateActive(Date value) {
        setAttributeInternal(STARTDATEACTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDateActive.
     * @return the EndDateActive
     */
    public Date getEndDateActive() {
        return (Date) getAttributeInternal(ENDDATEACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndDateActive.
     * @param value value to set the  EndDateActive
     */
    public void setEndDateActive(Date value) {
        setAttributeInternal(ENDDATEACTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin.
     * @param value value to set the  LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectVersionNumber.
     * @return the ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionNumber.
     * @param value value to set the  ObjectVersionNumber
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstName.
     * @return the FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstName.
     * @param value value to set the  FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastName.
     * @return the LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastName.
     * @param value value to set the  LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FullName.
     * @return the FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FullName.
     * @param value value to set the  FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyTypeMeaning.
     * @return the PropertyTypeMeaning
     */
    public String getPropertyTypeMeaning() {
        return (String) getAttributeInternal(PROPERTYTYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyTypeMeaning.
     * @param value value to set the  PropertyTypeMeaning
     */
    public void setPropertyTypeMeaning(String value) {
        setAttributeInternal(PROPERTYTYPEMEANING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonPropertyValueLov.
     * @return the PersonPropertyValueLov
     */
    public String getPersonPropertyValueLov() {
        return (String) getAttributeInternal(PERSONPROPERTYVALUELOV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonPropertyValueLov.
     * @param value value to set the  PersonPropertyValueLov
     */
    public void setPersonPropertyValueLov(String value) {
        setAttributeInternal(PERSONPROPERTYVALUELOV, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyValue.
     * @return the PropertyValue
     */
    public String getPropertyValue() {
        return (String) getAttributeInternal(PROPERTYVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyValue.
     * @param value value to set the  PropertyValue
     */
    public void setPropertyValue(String value) {
        setAttributeInternal(PROPERTYVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusMeaning.
     * @return the StatusMeaning
     */
    public String getStatusMeaning() {
        return (String) getAttributeInternal(STATUSMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusMeaning.
     * @param value value to set the  StatusMeaning
     */
    public void setStatusMeaning(String value) {
        setAttributeInternal(STATUSMEANING, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeesVO1.
     */
    public RowSet getEmployeesVO1() {
        return (RowSet)getAttributeInternal(EMPLOYEESVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeesLOVVO1.
     */
    public RowSet getEmployeesLOVVO1() {
        return (RowSet)getAttributeInternal(EMPLOYEESLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeesLOVVO2.
     */
    public RowSet getEmployeesLOVVO2() {
        return (RowSet)getAttributeInternal(EMPLOYEESLOVVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XxcusLookupValuesVO1.
     */
    public RowSet getXxcusLookupValuesVO1() {
        return (RowSet)getAttributeInternal(XXCUSLOOKUPVALUESVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
