package com.acme.paas.properties.model.adfbc.views;

import com.acme.paas.fwk.ViewRowImpl;

import com.acme.paas.properties.model.adfbc.entities.XxcusPersonPropertiesEOImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 15:53:16 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxcusPersonPropertiesEOVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PersonPropertyId {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPersonPropertyId();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPersonPropertyId((DBSequence)value);
            }
        }
        ,
        PersonId {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPersonId();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPersonId((Number)value);
            }
        }
        ,
        PersonPropertyType {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPersonPropertyType();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPersonPropertyType((String)value);
            }
        }
        ,
        PersonPropertyValue {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPersonPropertyValue();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPersonPropertyValue((String)value);
            }
        }
        ,
        Status {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        StartDateActive {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getStartDateActive();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setStartDateActive((Date)value);
            }
        }
        ,
        EndDateActive {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getEndDateActive();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setEndDateActive((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        FirstName {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getFirstName();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        LastName {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getLastName();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        FullName {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getFullName();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setFullName((String)value);
            }
        }
        ,
        PropertyTypeMeaning {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPropertyTypeMeaning();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPropertyTypeMeaning((String)value);
            }
        }
        ,
        PersonPropertyValueLov {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPersonPropertyValueLov();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPersonPropertyValueLov((String)value);
            }
        }
        ,
        PropertyValue {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getPropertyValue();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setPropertyValue((String)value);
            }
        }
        ,
        StatusMeaning {
            public Object get(XxcusPersonPropertiesEOVORowImpl obj) {
                return obj.getStatusMeaning();
            }

            public void put(XxcusPersonPropertiesEOVORowImpl obj,
                            Object value) {
                obj.setStatusMeaning((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxcusPersonPropertiesEOVORowImpl object);

        public abstract void put(XxcusPersonPropertiesEOVORowImpl object,
                                 Object value);

        public int index() {
            return XxcusPersonPropertiesEOVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return XxcusPersonPropertiesEOVORowImpl.AttributesEnum.firstIndex() + XxcusPersonPropertiesEOVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = XxcusPersonPropertiesEOVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERSONPROPERTYID = AttributesEnum.PersonPropertyId.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PERSONPROPERTYTYPE = AttributesEnum.PersonPropertyType.index();
    public static final int PERSONPROPERTYVALUE = AttributesEnum.PersonPropertyValue.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STARTDATEACTIVE = AttributesEnum.StartDateActive.index();
    public static final int ENDDATEACTIVE = AttributesEnum.EndDateActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int PROPERTYTYPEMEANING = AttributesEnum.PropertyTypeMeaning.index();
    public static final int PERSONPROPERTYVALUELOV = AttributesEnum.PersonPropertyValueLov.index();
    public static final int PROPERTYVALUE = AttributesEnum.PropertyValue.index();
    public static final int STATUSMEANING = AttributesEnum.StatusMeaning.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxcusPersonPropertiesEOVORowImpl() {
    }

    /**
     * Gets XxcusPersonPropertiesEO entity object.
     * @return the XxcusPersonPropertiesEO
     */
    public XxcusPersonPropertiesEOImpl getXxcusPersonPropertiesEO() {
        return (XxcusPersonPropertiesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PERSON_PROPERTY_ID using the alias name PersonPropertyId.
     * @return the PERSON_PROPERTY_ID
     */
    public DBSequence getPersonPropertyId() {
        return (DBSequence)getAttributeInternal(PERSONPROPERTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_PROPERTY_ID using the alias name PersonPropertyId.
     * @param value value to set the PERSON_PROPERTY_ID
     */
    public void setPersonPropertyId(DBSequence value) {
        setAttributeInternal(PERSONPROPERTYID, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PERSON_PROPERTY_TYPE using the alias name PersonPropertyType.
     * @return the PERSON_PROPERTY_TYPE
     */
    public String getPersonPropertyType() {
        return (String) getAttributeInternal(PERSONPROPERTYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_PROPERTY_TYPE using the alias name PersonPropertyType.
     * @param value value to set the PERSON_PROPERTY_TYPE
     */
    public void setPersonPropertyType(String value) {
        setAttributeInternal(PERSONPROPERTYTYPE, value);
    }

    /**
     * Gets the attribute value for PERSON_PROPERTY_VALUE using the alias name PersonPropertyValue.
     * @return the PERSON_PROPERTY_VALUE
     */
    public String getPersonPropertyValue() {
        return (String) getAttributeInternal(PERSONPROPERTYVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_PROPERTY_VALUE using the alias name PersonPropertyValue.
     * @param value value to set the PERSON_PROPERTY_VALUE
     */
    public void setPersonPropertyValue(String value) {
        setAttributeInternal(PERSONPROPERTYVALUE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for START_DATE_ACTIVE using the alias name StartDateActive.
     * @return the START_DATE_ACTIVE
     */
    public Date getStartDateActive() {
        return (Date) getAttributeInternal(STARTDATEACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE_ACTIVE using the alias name StartDateActive.
     * @param value value to set the START_DATE_ACTIVE
     */
    public void setStartDateActive(Date value) {
        setAttributeInternal(STARTDATEACTIVE, value);
    }

    /**
     * Gets the attribute value for END_DATE_ACTIVE using the alias name EndDateActive.
     * @return the END_DATE_ACTIVE
     */
    public Date getEndDateActive() {
        return (Date) getAttributeInternal(ENDDATEACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE_ACTIVE using the alias name EndDateActive.
     * @param value value to set the END_DATE_ACTIVE
     */
    public void setEndDateActive(Date value) {
        setAttributeInternal(ENDDATEACTIVE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstName.
     * @return the FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstName.
     * @param value value to set the  FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastName.
     * @return the LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastName.
     * @param value value to set the  LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FullName.
     * @return the FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FullName.
     * @param value value to set the  FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyTypeMeaning.
     * @return the PropertyTypeMeaning
     */
    public String getPropertyTypeMeaning() {
        return (String) getAttributeInternal(PROPERTYTYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyTypeMeaning.
     * @param value value to set the  PropertyTypeMeaning
     */
    public void setPropertyTypeMeaning(String value) {
        setAttributeInternal(PROPERTYTYPEMEANING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonPropertyValueLov.
     * @return the PersonPropertyValueLov
     */
    public String getPersonPropertyValueLov() {
        return (String) getAttributeInternal(PERSONPROPERTYVALUELOV);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonPropertyValueLov.
     * @param value value to set the  PersonPropertyValueLov
     */
    public void setPersonPropertyValueLov(String value) {
        setAttributeInternal(PERSONPROPERTYVALUELOV, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PropertyValue.
     * @return the PropertyValue
     */
    public String getPropertyValue() {
        return (String) getAttributeInternal(PROPERTYVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PropertyValue.
     * @param value value to set the  PropertyValue
     */
    public void setPropertyValue(String value) {
        setAttributeInternal(PROPERTYVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusMeaning.
     * @return the StatusMeaning
     */
    public String getStatusMeaning() {
        return (String) getAttributeInternal(STATUSMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusMeaning.
     * @param value value to set the  StatusMeaning
     */
    public void setStatusMeaning(String value) {
        setAttributeInternal(STATUSMEANING, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
