package com.acme.paas.properties.model.adfbc.views;

import com.acme.paas.fwk.ViewObjectImpl;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 15:53:24 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxcusPersonPropertiesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxcusPersonPropertiesVOImpl() {
    }

    /**
     * Returns the variable value for pPropertyTypeMeaning.
     * @return variable value for pPropertyTypeMeaning
     */
    public String getpPropertyTypeMeaning() {
        return (String)ensureVariableManager().getVariableValue("pPropertyTypeMeaning");
    }

    /**
     * Sets <code>value</code> for variable pPropertyTypeMeaning.
     * @param value value to bind as pPropertyTypeMeaning
     */
    public void setpPropertyTypeMeaning(String value) {
        ensureVariableManager().setVariableValue("pPropertyTypeMeaning", value);
    }

    /**
     * Returns the variable value for pFullName.
     * @return variable value for pFullName
     */
    public String getpFullName() {
        return (String)ensureVariableManager().getVariableValue("pFullName");
    }

    /**
     * Sets <code>value</code> for variable pFullName.
     * @param value value to bind as pFullName
     */
    public void setpFullName(String value) {
        ensureVariableManager().setVariableValue("pFullName", value);
    }

    /**
     * Returns the variable value for pEffectiveDate.
     * @return variable value for pEffectiveDate
     */
    public Date getpEffectiveDate() {
        return (Date)ensureVariableManager().getVariableValue("pEffectiveDate");
    }

    /**
     * Sets <code>value</code> for variable pEffectiveDate.
     * @param value value to bind as pEffectiveDate
     */
    public void setpEffectiveDate(Date value) {
        ensureVariableManager().setVariableValue("pEffectiveDate", value);
    }

    /**
     * Returns the variable value for pPersonNumber.
     * @return variable value for pPersonNumber
     */
    public String getpPersonNumber() {
        return (String)ensureVariableManager().getVariableValue("pPersonNumber");
    }

    /**
     * Sets <code>value</code> for variable pPersonNumber.
     * @param value value to bind as pPersonNumber
     */
    public void setpPersonNumber(String value) {
        ensureVariableManager().setVariableValue("pPersonNumber", value);
    }

    /**
     * Returns the variable value for pPreopertyValueMeaning.
     * @return variable value for pPreopertyValueMeaning
     */
    public String getpPreopertyValueMeaning() {
        return (String)ensureVariableManager().getVariableValue("pPreopertyValueMeaning");
    }

    /**
     * Sets <code>value</code> for variable pPreopertyValueMeaning.
     * @param value value to bind as pPreopertyValueMeaning
     */
    public void setpPreopertyValueMeaning(String value) {
        ensureVariableManager().setVariableValue("pPreopertyValueMeaning", value);
    }

    /**
     * Returns the variable value for pPropertyStatus.
     * @return variable value for pPropertyStatus
     */
    public String getpPropertyStatus() {
        return (String)ensureVariableManager().getVariableValue("pPropertyStatus");
    }

    /**
     * Sets <code>value</code> for variable pPropertyStatus.
     * @param value value to bind as pPropertyStatus
     */
    public void setpPropertyStatus(String value) {
        ensureVariableManager().setVariableValue("pPropertyStatus", value);
    }

    /**
     * Returns the variable value for pPropertyValue.
     * @return variable value for pPropertyValue
     */
    public String getpPropertyValue() {
        return (String)ensureVariableManager().getVariableValue("pPropertyValue");
    }

    /**
     * Sets <code>value</code> for variable pPropertyValue.
     * @param value value to bind as pPropertyValue
     */
    public void setpPropertyValue(String value) {
        ensureVariableManager().setVariableValue("pPropertyValue", value);
    }
}
